version: "3"
services:
  portfolio-app:
    image: jazzdocks/portfolio
    restart: always
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    